import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envLocalPath = join(root, ".env.local");
const legacyPath = join(root, "env.local");
const serviceJsonPath = join(root, "service.json");

if (existsSync(envLocalPath)) {
  console.log(".env.local already exists — skipping");
  process.exit(0);
}

let gemini = "";
let groq = "";

if (existsSync(legacyPath)) {
  const raw = readFileSync(legacyPath, "utf8");
  for (const line of raw.split(/\r?\n/)) {
    const [k, ...rest] = line.split("=");
    const v = rest.join("=").trim();
    if (k.trim() === "Gemini_API" || k.trim() === "GEMINI_API_KEY") gemini = v;
    if (k.trim() === "Groq_API" || k.trim() === "GROQ_API_KEY") groq = v;
  }
}

const hasServiceAccount = existsSync(serviceJsonPath);
const useMemory = hasServiceAccount ? "false" : "true";
const bypass = hasServiceAccount ? "false" : "true";

const content = `# Generated by scripts/prepare-env.mjs — do not commit
NODE_ENV=development
NEXT_PUBLIC_APP_URL=http://localhost:3000

USE_MEMORY_STORE=${useMemory}
DEV_AUTH_BYPASS=${bypass}
DEV_AUTH_UID=dev-user-1

ENABLE_CRITIC=true
ENABLE_JUDGE=true
ENABLE_CHALLENGEREADY_PACK=true

GEMINI_API_KEY=${gemini}
GROQ_API_KEY=${groq}

# Fill Firebase public values from console when ready
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=

# Preferred Admin wiring: gitignored service account file
FIREBASE_ADMIN_CREDENTIALS_PATH=${hasServiceAccount ? "./service.json" : ""}
GOOGLE_APPLICATION_CREDENTIALS=${hasServiceAccount ? "./service.json" : ""}
FIREBASE_ADMIN_PROJECT_ID=
FIREBASE_ADMIN_CLIENT_EMAIL=
FIREBASE_ADMIN_PRIVATE_KEY=
`;

writeFileSync(envLocalPath, content, "utf8");
console.log(
  hasServiceAccount
    ? "Wrote .env.local (connected-mode flags; fill NEXT_PUBLIC_FIREBASE_* )"
    : "Wrote .env.local (memory store + mapped AI keys if present)"
);
